export default {
  trkz: {
    loading: 'Yükleniyor',
    language: 'Dil',
    languageDisplayText: 'Türkçe',
    darkTheme: 'Koyu Tema',
    error: 'Hata | Hatalar',
    default: 'Varsayılan',
    notes: 'Açıklama',
    apply: 'Uygula',
    yes: 'Evet',
    no: 'Hayır',
    on: 'Açık',
    off: 'Kapalı',
    true: 'Doğru',
    false: 'Yanlış',
    active: 'Aktif',
    passive: 'Pasif',
    cancel: 'Vazgeç',
    clear: 'Temizle',
    reset: 'Sıfırla',
    back: 'Geri',
    save: 'Kaydet',
    delete: 'Sil',
    deleteAll: 'Tümünü Sil',
    info: 'Bilgi',
    set: 'Ata',
    assign: 'Ata',
    assigned: 'Atanmış',
    unassign: 'Atamayı Kaldır',
    unassigned: 'Atanmamış',
    search: 'Arama',
    saveSucceeded: 'Kaydetme işlemi başarıyla tamamlandı.',
    pleaseStandby: 'Lütfen bekleyin...',
    operationFinishSuccessfully: 'İşlem başarıyla tamamlandı.',
    dataWasSuccessfullySaved: 'Veri({entity}) başarılı şekilde kaydedilmiştir.',
    dataWasntChanged: 'Veride değişiklik yapılmamıştır.',
    operationFinishWithError: 'İşlem başarısız oldu.',
    confirmationRequired: 'Onayınıza ihtiyacımız var',
    confirmDeletionQuestion: 'Seçmiş olduğunuz kayıt(lar)ın silinmesini onaylıyor musunuz?',
    chassisNo: 'Şasi No',
    topModel: 'Üst Model',
    declarationNo: 'Beyanname No',
    pickUpLocation: 'Alınma Noktası',
    deliveryLocation: 'Teslim Noktası',
    none: '<Yok>',
    add: 'Ekle',
    close: 'Kapat',
    address: 'Adres',
    except: 'Hariç',
    packingSlip: 'Sevk İrsaliyesi',
    createdAt: 'Oluşturulma Tarihi',
    createdBy: 'Oluşturan',
    updateAt: 'Değişiklik Tarihi',
    updateBy: 'Değiştiren',
    emptyFilterError: 'Filtre Boş Olamaz.',
    currency: {
      singular: 'Para Birimi',
      try: 'TRY',
      usd: 'USD',
      aud: 'AUD',
      dkk: 'DKK',
      eur: 'EUR',
    },
    wizard: {
      previous: 'Önceki',
      next: 'Sonraki',
      complete: 'Tamamla',
    },
    dataTable: {
      commands: {
        display: 'Göster',
        edit: 'Değiştir',
        delete: 'Sil',
        add: 'Ekle',
        showHideColumns: 'Gösterilecek Kolonlar',
        filter: 'Filtreleme',
        select: 'Seç',
        selectAll: 'Hepsini Seç',
        dataViews: 'Veri Görünümleri',
      },
      columns: {
        id: 'Kimlik',
        key: 'Kod',
        title: 'Başlık',
        isActive: 'Aktif mi?',
        createdAt: 'Oluşturulma Tarihi',
        createdBy: 'Oluşturan',
        modifiedAt: 'Değiştirilme Tarihi',
        modifiedBy: 'Değiştiren',
        total: 'Toplam',
      },
      addNewFilter: 'Yeni Filtre',
      column: 'Kolon',
      filter: {
        string: {
          text: 'Yazı',
          eq: 'Eşit',
          neq: 'Eşit değil',
          contains: 'İçerir',
          startsWith: 'Başlar',
          endsWith: 'Biter',
          g: '>',
          ge: '>=',
          l: '<',
          le: '<=',
        },
        number: {
          text: 'Sayı',
          eq: 'Eşit',
          neq: 'Eşit değil',
          g: '>',
          ge: '>=',
          l: '<',
          le: '<=',
        },
        date: {
          text: 'Tarih',
          eq: 'Eşit',
          neq: 'Eşit değil',
          g: '>',
          ge: '>=',
          l: '<',
          le: '<=',
        },
      },
    },
    validationMessages: {
      required: 'Boş bırakamazsınız!',
      minFrom: '{0} alanından küçük olmalıdır.',
      maxFrom: '{0} alanından büyük olmalıdır.',
      minFromValue: '{0} değerinden küçük olmalıdır.',
      maxFromValue: '{0} değerinden büyük olmalıdır.',
      exactLength: 'Bu alan tam {0} karakter uzunluğunda olmalıdır.',
      platePattern: 'Girilen plaka yanlış formattadır.',
      chassisPattern: 'Girilen şase numarası yanlış formattadır.',
    },
    errors: {
      networkError: 'Bağlantı Hatası : %s',
    },
    logout: 'Çıkış',
  },
};
