export default {
  trkz: {
    loading: 'Loading',
    language: 'Language',
    languageDisplayText: 'English',
    darkTheme: 'Dark Theme',
    error: 'Error | Errors',
    default: 'Default',
    notes: 'Notes',
    apply: 'Apply',
    yes: 'Yes',
    no: 'No',
    on: 'On',
    off: 'Off',
    true: 'True',
    false: 'False',
    active: 'Active',
    passive: 'Passive',
    cancel: 'Cancel',
    clear: 'Clear',
    reset: 'Reset',
    back: 'Back',
    save: 'Save',
    delete: 'Delete',
    deleteAll: 'Delete All',
    info: 'Information',
    set: 'Set',
    assign: 'Assign',
    assigned: 'Assigned',
    unassign: 'Unassign',
    unassigned: 'Unassigned',
    search: 'Search',
    saveSucceeded: 'Save succeeded.',
    pleaseStandby: 'Please stand by...',
    operationFinishSuccessfully: 'Operation succeeded.',
    dataWasSuccessfullySaved: 'Data({entity}) was successfully saved.',
    dataWasntChanged: 'Data wasn\'t changed.',
    operationFinishWithError: 'Operation Failed.',
    confirmationRequired: 'We need your confirmation',
    confirmDeletionQuestion: 'Do you approve the deletion of the selected record(s)?',
    chassisNo: 'Chassis No',
    topModel: 'Üst Model',
    declarationNo: 'Declaration No',
    pickUpLocation: 'Pick Up Location',
    deliveryLocation: 'Delivery Location',
    none: '<None>',
    add: 'Add',
    close: 'Close',
    address: 'Address',
    except: 'Except',
    packingSlip: 'Packing Slip',
    createdAt: 'Created At',
    createdBy: 'Created By',
    updateAt: 'Update At',
    updateBy: 'Update By',
    emptyFilterError: 'Filter could not be empty.',
    currency: {
      singular: 'Currency',
      try: 'TRY',
      usd: 'USD',
      aud: 'AUD',
      dkk: 'DKK',
      eur: 'EUR',
    },
    wizard: {
      previous: 'Önceki',
      next: 'Sonraki',
      complete: 'Tamamla',
    },
    dataTable: {
      commands: {
        display: 'Display',
        edit: 'Edit',
        delete: 'Delete',
        add: 'Add',
        showHideColumns: 'Show/Hide Columns',
        filter: 'Filter',
        select: 'Select',
        selectAll: 'Select All',
        dataViews: 'Data Views',
      },
      columns: {
        id: 'Id',
        key: 'Key',
        title: 'Title',
        isActive: 'Is Active?',
        createdAt: 'Created At',
        createdBy: 'Created At',
        modifiedAt: 'Modified At',
        modifiedBy: 'Modified At',
        total: 'Total',
      },
      addNewFilter: 'New Filter',
      column: 'Column',
      filter: {
        string: {
          text: 'Text',
          eq: 'Equals',
          neq: 'Not equals',
          contains: 'Contains',
          startsWith: 'Starts with',
          endsWith: 'Ends with',
          g: '>',
          ge: '>=',
          l: '<',
          le: '<=',
        },
        number: {
          text: 'Number',
          eq: 'Eşit',
          neq: 'Eşit değil',
          g: '>',
          ge: '>=',
          l: '<',
          le: '<=',
        },
        date: {
          text: 'Date',
          eq: 'Eşit',
          neq: 'Eşit değil',
          g: '>',
          ge: '>=',
          l: '<',
          le: '<=',
        },
      },
    },
    validationMessages: {
      required: 'This field is required!',
      minFrom: 'This field must be less then {0} field.',
      maxFrom: 'This field must be greater then {0} field.',
      minFromValue: 'This field must be less then {0} value.',
      maxFromValue: 'This field must be greater then {0} value.',
      exactLength: 'This field must be exactly {0} character length.',
      platePattern: 'Plate pattern is not correct format.',
      chassisPattern: 'Chassis pattern is not correct format.',
    },
    errors: {
      networkError: 'Network Error : %s',
    },
    logout: 'Log out',
  },
};
