export enum CurrencyTypes {
    TRY = "TRY",
    USD = "USD",
    AUD = "AUD",
    DKK = "DKK",
    EUR = "EUR",
    GBP = "GBP",
    CHF = "CHF",
    SEK = "SEK",
    CAD = "CAD",
    KWD = "KWD",
    NOK = "NOK",
    SAR = "SAR",
    JPY = "JPY",
    BGN = "BGN",
    RON = "RON",
    RUB = "RUB",
    IRR = "IRR",
    CNY = "CNY",
    PKR = "PKR",
  }
